### ISSUE TITLE
Question delete/create

### ISSUE THREAD

**Issue by alexis-magina** [isotopsweden/wp-syncs#1]
Hello,

I'm studying your plugin for use it on personal project and I have a little question :
Is there a specific reason why you prefer delete and re-create objects on other multisites in case of updates ?
In my project, I have posts attached to each others, so changing post_ids complicates a lot the process, and it seems unnecessary for me : it would be better to update directly sync posts with updated content. 

Is there something that I did not think, and which make the deletion / creation absolutly necessary?

**Comment by frozzare** [comment]
Hi,

Yes, I don't remember why we decided to recreate and not update objects but for the sites that this plugin (but I'm sure that we had a good reason to it like that) is built we only use the wp admin as a headless cms. So when using this you can't use object ids as a key and thing it will work, because it won't. You have to use the sync id everywhere, if you have custom fields stuff or something like this you have to store the sync id and not the object ids, so this plugin will not work with all plugins and that's not our goal.

If you would like a different behavior in the plugin you can always fork it :)
